test_mirror: do not use a fixed port for the internal test server
The tests were fairly consistently failing with:
  error: [Errno 98] Address already in use

Actually the port is a well-known port that could be used be some other
program. So let's simplify things by opening a random port.

It'd be nice to use the socket as a context manager, but unfortunately
python2 does not support that.