Prevent error due bytes when grabbing local paths
>>> urlgrabber.urlgrab("file://tmp/foobar/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/urlgrabber/grabber.py", line 806, in urlgrab
    return default_grabber.urlgrab(url, filename, **kwargs)
  File "/usr/lib/python3.6/site-packages/urlgrabber/grabber.py", line 1216, in urlgrab
    path = url2pathname(path)
  File "/usr/lib64/python3.6/urllib/request.py", line 1684, in url2pathname
    return unquote(pathname)
  File "/usr/lib64/python3.6/urllib/parse.py", line 640, in unquote
    if '%' not in string:
TypeError: a bytes-like object is required, not 'str'