py3: avoid "unbound variable" issue
Under python3, the variable defined in "except ... as ..." is only
valid until the end of the block. In this case it would undefine the
variable that was defined above, not reassign it as under python2,
leading to the following tb:

Traceback (most recent call last):
  File "test/test_mirror.py", line 379, in test_retry_no_cache
    urlgrabber.grabber.parallel_wait()
  File "test/../urlgrabber/grabber.py", line 2374, in parallel_wait
    perform()
  File "test/../urlgrabber/grabber.py", line 2313, in perform
    if ug_err is None:
UnboundLocalError: local variable 'ug_err' referenced before assignment